// <auto-generated />
using DoctorClinicApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorClinicApplication.Migrations
{
    [DbContext(typeof(DoctorClinicContext))]
    [Migration("20240514105022_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoctorClinicApplication.Modals.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Age = 25,
                            Experience = 12,
                            Name = "Kavin",
                            Qualification = "MBBS.,",
                            Speciality = "Cardio"
                        },
                        new
                        {
                            Id = 102,
                            Age = 35,
                            Experience = 15,
                            Name = "Pravin",
                            Qualification = "MBBS.,",
                            Speciality = "Ortho"
                        },
                        new
                        {
                            Id = 103,
                            Age = 45,
                            Experience = 22,
                            Name = "Raja",
                            Qualification = "MBBS.,M.sc.,",
                            Speciality = "Cardio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
