version: "3"

services:
  mongodb:
    image: mongo:latest  # Use the latest mongo image
    container_name: my-mongodb
    restart: unless-stopped  # Restart container on failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Set environment variable for username
      MONGO_INITDB_ROOT_PASSWORD: password  # Set environment variable for password
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  nodeapp:
    build: .
    container_name : my-node-app
    ports:
       - "3000:3000"
    depends_on:
       - mongodb
    environment:
       MONGO_URL: mongodb://my-mongodb:27017/mydatabase

  mongo-express:
    image: mongo-express  # Use the mongo-express image
    container_name : mongo-express
    restart: unless-stopped  # Restart container on failure
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081
    depends_on:
      - mongodb  # Wait for mongo to be ready before starting mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb  # Set MongoDB server name (service name)
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin  # Set Mongo-Express username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password  # Set Mongo-Express password

volumes:
  mongo-data:  # Named volume to persist MongoDB data
